export const audioMap = {
  "Welcome to the Global Estimation Squad!": "/assets/audio/audio_welcome_to_the_global_estimation_squad__0.mp3",
  "Today, we are going to master rounding and estimation across world landmarks.": "/assets/audio/audio_today__we_are_going_to_master_rounding_a_1.mp3",
  "How can rounding help us find quick, reasonable answers without counting every single thing?": "/assets/audio/audio_how_can_rounding_help_us_find_quick__rea_2.mp3",
  "Are you ready to join the squad and explore estimation challenges? Let us get started!": "/assets/audio/audio_are_you_ready_to_join_the_squad_and_expl_3.mp3",
  "42,187 people are at a stadium in Rio de Janeiro. Sarah needs to tell her friend about how many people were there without counting every single one. What should she say?": "/assets/audio/audio_42_187_people_are_at_a_stadium_in_rio_de_4.mp3",
  "Forty-two thousand one hundred eighty-seven people are at a stadium in Rio de Janeiro. Sarah needs to tell her friend about how many people were there without counting every single one. What should she say?": "/assets/audio/audio_forty_two_thousand_one_hundred_eighty_se_5.mp3",
  "When numbers are huge or exact counts take too long, rounding and estimation give us fast, smart answers!": "/assets/audio/audio_when_numbers_are_huge_or_exact_counts_ta_6.mp3",
  "Let us discover how rounding and estimation give us real-world superpowers!": "/assets/audio/audio_let_us_discover_how_rounding_and_estimat_7.mp3",
  "John, Mike, Sarah, Emma, Liam, Sofia, Noah, Aisha, Carlos, and Yuki form the Global Estimation Squad. They love using smart estimates in everyday life!": "/assets/audio/audio_john__mike__sarah__emma__liam__sofia__no_8.mp3",
  "John, Mike, Sarah, Emma, Liam, Sofia, Noah, Aisha, Carlos, and Yuki form the Global Estimation Squad — using smart rounding & estimation to solve everyday math mysteries in cities around the world!": "/assets/audio/audio_john__mike__sarah__emma__liam__sofia__no_9.mp3",
  "Mike is shopping in New York. His cart shows $18.75, $6.40, and $11.20. About how much will he pay altogether?": "/assets/audio/audio_mike_is_shopping_in_new_york__his_cart_s_10.mp3",
  "Mike is shopping in New York. His cart shows eighteen dollars and seventy-five cents, six dollars and forty cents, and eleven dollars and twenty cents. About how much will he pay altogether?": "/assets/audio/audio_mike_is_shopping_in_new_york__his_cart_s_11.mp3",
  "Rounding each price to the nearest dollar makes $18.75 about $19, $6.40 about $6, and $11.20 about $11. Nineteen plus six plus eleven is about $36 altogether!": "/assets/audio/audio_rounding_each_price_to_the_nearest_dolla_12.mp3",
  "Rounding each price to the nearest dollar makes eighteen seventy-five about nineteen dollars, six forty about six dollars, and eleven twenty about eleven dollars. Nineteen plus six plus eleven is about thirty-six dollars!": "/assets/audio/audio_rounding_each_price_to_the_nearest_dolla_13.mp3",
  "Priya in Mumbai reads that a passenger train has 3,912 seats. She rounds it to the nearest thousand: about 4,000 seats!": "/assets/audio/audio_priya_in_mumbai_reads_that_a_passenger_t_14.mp3",
  "Priya in Mumbai reads that a passenger train has three thousand nine hundred twelve seats. She rounds it to the nearest thousand: about four thousand seats!": "/assets/audio/audio_priya_in_mumbai_reads_that_a_passenger_t_15.mp3",
  "Diego checks his math homework: 396 × 21. Using compatible numbers, 400 × 20 = 8,000! His exact answer should be close to that.": "/assets/audio/audio_diego_checks_his_math_homework__396___21_16.mp3",
  "Diego checks his math homework: three hundred ninety-six times twenty-one. Using compatible numbers, four hundred times twenty equals eight thousand! His exact answer should be close to that.": "/assets/audio/audio_diego_checks_his_math_homework__three_hu_17.mp3",
  "Every city, every receipt, every big calculation: rounding and estimation help us think fast, budget wisely, and check our work!": "/assets/audio/audio_every_city__every_receipt__every_big_cal_18.mp3",
  "Slide the number along the number line. Which benchmark tick is it closest to? Watch the marker snap into place!": "/assets/audio/audio_slide_the_number_along_the_number_line___19.mp3",
  "Look at the four estimation cards. Tap the cards that show a reasonable estimate for the pictured quantity!": "/assets/audio/audio_look_at_the_four_estimation_cards__tap_t_20.mp3",
  "Fill in the missing blank in the estimation equation using the number pad!": "/assets/audio/audio_fill_in_the_missing_blank_in_the_estimat_21.mp3",
  "Perfect snap! You found the exact benchmark!": "/assets/audio/audio_perfect_snap__you_found_the_exact_benchm_22.mp3",
  "42,187 is closer to 42,000 because 187 is less than the halfway mark of 500!": "/assets/audio/audio_42_187_is_closer_to_42_000_because_187_i_23.mp3",
  "3,912 has a 9 in the hundreds place (≥ 500), magnetically snapping up to 4,000!": "/assets/audio/audio_3_912_has_a_9_in_the_hundreds_place____5_24.mp3",
  "7.86 is closer to 7.90 than 7.80 because the hundredths digit is 6 (≥ 5).": "/assets/audio/audio_7_86_is_closer_to_7_90_than_7_80_because_25.mp3",
  "19,500 lands exactly on the midpoint (500). Standard mathematical convention rounds UP to 20,000!": "/assets/audio/audio_19_500_lands_exactly_on_the_midpoint__50_26.mp3",
  "Great math! You completed the compatible equation!": "/assets/audio/audio_great_math__you_completed_the_compatible_27.mp3",
  "Spot on! You picked every reasonable estimate!": "/assets/audio/audio_spot_on__you_picked_every_reasonable_est_28.mp3",
  "Great job! That estimate is right on target!": "/assets/audio/audio_great_job__that_estimate_is_right_on_tar_29.mp3",
  "Not quite. Let us check the benchmark numbers and try again!": "/assets/audio/audio_not_quite__let_us_check_the_benchmark_nu_30.mp3",
  "Let us reflect on what we learned! Can you help teach Rounder the core ideas of rounding and estimation?": "/assets/audio/audio_let_us_reflect_on_what_we_learned__can_y_31.mp3",
  "Spot on! That explains rounding and estimation clearly!": "/assets/audio/audio_spot_on__that_explains_rounding_and_esti_32.mp3",
  "Think about how benchmark numbers help us approximate reasonable values.": "/assets/audio/audio_think_about_how_benchmark_numbers_help_u_33.mp3",
  "How confident do you feel about rounding and estimation? Every answer is great!": "/assets/audio/audio_how_confident_do_you_feel_about_rounding_34.mp3",
  "Look closely at the distances from the midpoint.": "/assets/audio/audio_look_closely_at_the_distances_from_the_m_35.mp3",
  "400 and 20 are super compatible! Mental multiplication takes less than 2 seconds.": "/assets/audio/audio_400_and_20_are_super_compatible__mental__36.mp3",
  "400 ÷ 20 = 20 gives an instant sanity check before diving into long division.": "/assets/audio/audio_400___20___20_gives_an_instant_sanity_ch_37.mp3",
  "900 − 400 = 500 lets you immediately verify reasonable change or budget estimates.": "/assets/audio/audio_900___400___500_lets_you_immediately_ver_38.mp3",
  "400 × 20 = 8,000.": "/assets/audio/audio_400___20___8_000__39.mp3",
  "400 ÷ 20 = 20.": "/assets/audio/audio_400___20___20__40.mp3",
  "$19 + $11 = $30.": "/assets/audio/audio__19____11____30__41.mp3",
  "Incredible! You are on a 5 question streak! Perfect estimate!": "/assets/audio/audio_incredible__you_are_on_a_5_question_stre_42.mp3"
};
